spring.application.name=portfoliobackend

spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.alicloud.tidbcloud.com:4000/portfolio_db
spring.datasource.username=kkL5HmNkN2yyfo3.root
spring.datasource.password=U1P1Jl88m3lOvgqm

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
